# Generated by Django 3.1.6 on 2021-02-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='id',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
